### ISSUE TITLE
I am not able to clone labkey compliance repo  

### ISSUE THREAD

**Issue by kaviyarasu7** [PopMedNet-Team/FDA-My-Studies-Mobile-Application-System#4]
I am trying to setup labkey server for FDA mobile app setup but when I am trying to clone https://github.com/LabKey/compliance I do not seems to clone it's private.

Any help here?

**Comment by jason-t14** [comment]
@PopMedNet-Team any update on this issue? I am facing the same issue. Thanks!

**Comment by FDA-MyStudies** [comment]
@kaviyarasu7 , @jason-t14 

At this time, the the compliance module is in a private repo that isn't available for cloning by the general public. However, the module is not required for either the Registration or Response server to function. For now, you can ignore the instruction and comment out the line in the distribution file(s) that references compliance.module.
