### ISSUE TITLE
what file to start at to view the documentation

### ISSUE THREAD

**Issue by vojtechhuser** [PopMedNet-Team/FDA-My-Studies-Mobile-Application-System#6]
In the documentation folder - it is not clear what file is the starting point.

something like index.html ?

**Comment by vojtechhuser** [comment]
ideally, provide a link in readme.md using this info
https://stackoverflow.com/questions/8446218/how-to-see-an-html-page-on-github-as-a-normal-rendered-html-page-to-see-preview

**Comment by FDA-MyStudies** [comment]
@vojtechhuser  

Thank you for your interest in the MyStudies system. We recommend starting with the code and documents needed for the mobile application. 

Please note, we are currently working with our developers to further address your question as well as the other questions and comments that have been posted to our repository. We'll have more updates later this spring.

**Comment by vojtechhuser** [comment]
any update?

**Comment by FDA-MyStudies** [comment]
@vojtechhuser 

We plan to post updated source code this week.  I am closing this issue for now, but please feel free to re-open or open a new issue with further questions.
